# Generated by Django 5.0.6 on 2024-06-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('application_processed', models.BooleanField(default=False, verbose_name='Заявка обработана')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес')),
                ('floor', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Этаж')),
                ('working_hours', models.CharField(blank=True, max_length=500, null=True, verbose_name='Время работы')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('fact_description', models.CharField(max_length=500, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название дома')),
                ('facade', models.CharField(blank=True, max_length=500, null=True, verbose_name='Фасад')),
                ('square', models.CharField(blank=True, max_length=500, null=True, verbose_name='Площадь')),
                ('room', models.CharField(blank=True, max_length=500, null=True, verbose_name='Количество комнат')),
                ('bathroom', models.CharField(blank=True, max_length=500, null=True, verbose_name='Количество санузлов')),
                ('floor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Количество этажей')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание дома')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Главное изображение')),
                ('cost_of_basic_equipment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стоимость базовой комплектации')),
                ('building_materials_equipment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стоимость стройматериалов')),
            ],
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, verbose_name='Материал стен')),
            ],
        ),
        migrations.CreateModel(
            name='InfoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_on_the_market', models.IntegerField(verbose_name='Лет на рынке недвижимости')),
                ('satisfied_clients', models.IntegerField(verbose_name='Довольных клиентов')),
                ('number_of_reviews', models.IntegerField(verbose_name='Количество отзывов')),
                ('the_number_of_employees', models.IntegerField(verbose_name='Количество сотрудников')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_partner', models.CharField(max_length=500, verbose_name='Имя партнера')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10, verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='SignUpForAFreeConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('date_of_consultation', models.DateField(verbose_name='Дата')),
                ('application_processed', models.BooleanField(default=False, verbose_name='Заявка обработана')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_social_media', models.CharField(max_length=500, verbose_name='Социальная сеть')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('image', models.FileField(upload_to='', verbose_name='Иконка')),
            ],
        ),
        migrations.CreateModel(
            name='HouseFacadePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Изображение фасада дома')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.house', verbose_name='Дом')),
            ],
        ),
        migrations.CreateModel(
            name='HousePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.house', verbose_name='Дом')),
            ],
        ),
        migrations.CreateModel(
            name='HousePlanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Изображение плана дома')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.house', verbose_name='Дом')),
            ],
        ),
        migrations.CreateModel(
            name='HouseSectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Изображение дома в разрезе')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.house', verbose_name='Дом')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.housetype', verbose_name='Материал стен'),
        ),
    ]
