# Generated by Django 5.0.6 on 2024-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_backgroundsliderimage_alter_house_main_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка'),
        ),
    ]
