# Generated by Django 5.0.6 on 2024-06-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_socialmedia_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='working_days',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочие дни'),
        ),
    ]
