# Generated by Django 5.0.6 on 2024-06-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact_working_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='link',
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона/ссылка на соц сеть'),
        ),
    ]
