# Generated by Django 5.0.6 on 2024-06-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_socialmedia_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
