# Generated by Django 5.0.6 on 2024-06-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_house_link_to_video_on_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_photo', models.ImageField(upload_to='improvement_main_photo', verbose_name='Главное изображение')),
            ],
        ),
    ]
