# Generated by Django 5.0.6 on 2024-06-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_improvement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='improvement_photos', verbose_name='Изображение')),
                ('improvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.improvement', verbose_name='Благоустройство')),
            ],
        ),
    ]
