# Generated by Django 5.0.6 on 2024-06-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_improvementphoto'),
        ('main', '0009_review'),
    ]

    operations = [
    ]
