# Generated by Django 5.0.6 on 2024-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_0009_improvementphoto_0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('fact_description', models.CharField(max_length=500, verbose_name='Текст')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
        ),
    ]
