# Generated by Django 5.0.6 on 2024-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundsliderimage',
            options={'verbose_name': 'Изображение в карусели банера сайта', 'verbose_name_plural': 'Изображения в карусели банера сайта'},
        ),
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Заявка на обратный звонок', 'verbose_name_plural': 'Заявки на обратный звонок'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Наши контакты', 'verbose_name_plural': 'Наши контакты'},
        ),
        migrations.AlterModelOptions(
            name='fact',
            options={'verbose_name': 'Факт о нас', 'verbose_name_plural': 'Факты о нас'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Проект дома', 'verbose_name_plural': 'Проекты домов'},
        ),
        migrations.AlterModelOptions(
            name='housefacadephoto',
            options={'verbose_name': 'Изображение фасада проекта (дома)', 'verbose_name_plural': 'Изображения фасадов проекта (дома)'},
        ),
        migrations.AlterModelOptions(
            name='housephoto',
            options={'verbose_name': 'Дополнительная фотография дома', 'verbose_name_plural': 'Дополнительные фотографии дома'},
        ),
        migrations.AlterModelOptions(
            name='houseplanphoto',
            options={'verbose_name': 'Изображение плана проекта (дома)', 'verbose_name_plural': 'Изображения плана проекта (дома)'},
        ),
        migrations.AlterModelOptions(
            name='housetype',
            options={'verbose_name': 'Тип дома', 'verbose_name_plural': 'Типы домов'},
        ),
        migrations.AlterModelOptions(
            name='improvement',
            options={'verbose_name': 'Вид работ по благоустройству', 'verbose_name_plural': 'Виды работ по благоустройству'},
        ),
        migrations.AlterModelOptions(
            name='improvementphoto',
            options={'verbose_name': 'Дополнительное изображение благоустройства', 'verbose_name_plural': 'Дополнительные изображения благоустройства'},
        ),
        migrations.AlterModelOptions(
            name='infocompany',
            options={'verbose_name': 'Информация о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Наш партнер', 'verbose_name_plural': 'Наши партнеры'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг по отзывам на яндекс картах', 'verbose_name_plural': 'Рейтинг по отзывам на яндекс картах'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='signupforafreeconsultation',
            options={'verbose_name': 'Заявка на консультацию', 'verbose_name_plural': 'Заявки на консультацию'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='signupforafreeconsultation',
            name='date_of_consultation',
            field=models.DateField(verbose_name='Дата консультации'),
        ),
        migrations.DeleteModel(
            name='HouseSectionPhoto',
        ),
    ]
