# Generated by Django 5.0.6 on 2024-06-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_backgroundsliderimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocompany',
            name='photo_ours_employer',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото наших сотрудников'),
        ),
    ]
