# Generated by Django 5.0.6 on 2024-06-18 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_infocompany_photo_ours_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundsliderimage',
            name='image',
            field=models.FileField(help_text='Изображение должно быть в формате avif, преобразовать можно <a href="https://imagetostl.com/ru/convert/file/jpg/to/avif">тут</a>', upload_to='background_images', validators=[django.core.validators.FileExtensionValidator(['avif'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='house',
            name='main_photo',
            field=models.FileField(blank=True, help_text='Изображение должно быть в формате avif, преобразовать можно <a href="https://imagetostl.com/ru/convert/file/jpg/to/avif">тут</a>', null=True, upload_to='house_main_photos', validators=[django.core.validators.FileExtensionValidator(['avif'])], verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='housefacadephoto',
            name='photo',
            field=models.FileField(help_text='Изображение должно быть в формате avif, преобразовать можно <a href="https://imagetostl.com/ru/convert/file/jpg/to/avif">тут</a>', upload_to='house_facade_photos', validators=[django.core.validators.FileExtensionValidator(['avif'])], verbose_name='Изображение фасада дома'),
        ),
        migrations.AlterField(
            model_name='housephoto',
            name='photo',
            field=models.FileField(help_text='Изображение должно быть в формате avif, преобразовать можно <a href="https://imagetostl.com/ru/convert/file/jpg/to/avif">тут</a>', upload_to='house_photos', validators=[django.core.validators.FileExtensionValidator(['avif'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='houseplanphoto',
            name='photo',
            field=models.FileField(help_text='Изображение должно быть в формате avif, преобразовать можно <a href="https://imagetostl.com/ru/convert/file/jpg/to/avif">тут</a>', upload_to='house_plan_photos', validators=[django.core.validators.FileExtensionValidator(['avif'])], verbose_name='Изображение плана дома'),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='main_photo',
            field=models.FileField(help_text='Изображение должно быть в формате avif, преобразовать можно <a href="https://imagetostl.com/ru/convert/file/jpg/to/avif">тут</a>', upload_to='improvement_main_photo', validators=[django.core.validators.FileExtensionValidator(['avif'])], verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='improvementphoto',
            name='photo',
            field=models.FileField(help_text='Изображение должно быть в формате avif, преобразовать можно <a href="https://imagetostl.com/ru/convert/file/jpg/to/avif">тут</a>', upload_to='improvement_photos', validators=[django.core.validators.FileExtensionValidator(['avif'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='infocompany',
            name='photo_ours_employer',
            field=models.FileField(blank=True, help_text='Изображение должно быть в формате avif, преобразовать можно <a href="https://imagetostl.com/ru/convert/file/jpg/to/avif">тут</a>', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['avif'])], verbose_name='Фото наших сотрудников'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.FileField(help_text='Изображение должно быть в формате avif, преобразовать можно <a href="https://imagetostl.com/ru/convert/file/jpg/to/avif">тут</a>', upload_to='reviews_photo', validators=[django.core.validators.FileExtensionValidator(['avif'])], verbose_name='Изображение'),
        ),
    ]
